//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionContent()
        {
            this.Comments = new HashSet<Comment>();
            this.QuestionContentVotes = new HashSet<QuestionContentVote>();
        }
    
        public int QuestionContentId { get; set; }
        public int SubCategoryId { get; set; }
        public string QuestionTiltle { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Answer { get; set; }
        public string QuestionDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionContentVote> QuestionContentVotes { get; set; }
    }
}
