//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AuditLogs = new HashSet<AuditLog>();
            this.Comments = new HashSet<Comment>();
            this.DebugLogs = new HashSet<DebugLog>();
            this.Rates = new HashSet<Rate>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public int PasswordSalt { get; set; }
        public bool Confirmation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserTypeId { get; set; }
        public int AgeRangeId { get; set; }
        public int TitleId { get; set; }
        public int GenderId { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual AdditionalUserInfo AdditionalUserInfo { get; set; }
        public virtual AgeRanx AgeRanx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebugLog> DebugLogs { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
        public virtual State State { get; set; }
        public virtual Title Title { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
